version: '3'
services:

  tbng-bridge:
    restart: unless-stopped
    image: tbng-tor
    hostname: tor
    ports:
      - 4443:4443 
    healthcheck:
      test: ["CMD", "curl", "--fail", "--socks5", "127.0.0.1:9050","https://torproject.org"]
      interval: 30s
      timeout: 10s
      retries: 10 
    volumes:
      - bridgeconf:/opt/torconf
      - bridgedata:/var/lib/tor
    mem_limit: 160m
    cpus: 0.5

  tbng-3proxy:
    restart: unless-stopped
    image: tbng-3proxy_ds
    links: 
      - tbng-bridge:tor
    ports:
      - 8888:8888
      - 10800:1080
    environment:
      - AUTH=${AUTH}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
    depends_on:
      tbng-bridge:
        condition: service_healthy
    mem_limit: 32m
    cpus: 0.5

volumes:
  bridgeconf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/conf/tbng-bridge"
  bridgedata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/data/tbng-bridge"
