version: '3'
services:

  tbng-bridge:
    restart: unless-stopped
    image: tbng-tor
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "--fail", "--socks5", "127.0.0.1:9050","https://torproject.org"]
      interval: 30s
      timeout: 10s
      retries: 10 
    volumes:
     - bridgeconf:/opt/torconf
    mem_limit: 128m
    cpus: 0.5

  tbng-3proxy:
    restart: unless-stopped
    image: tbng-3proxy_ds
    network_mode: host
    environment:
      - AUTH=${AUTH}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
    depends_on:
      tbng-bridge:
        condition: service_healthy
    mem_limit: 32m
    cpus: 0.5

volumes:
  bridgeconf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/conf/tbng-bridge"
