version: '3'
services:

  tbng-bridge:
    restart: unless-stopped
    image: tbng-tor
    ports:
     - "4443:4443" 
    healthcheck:
      test: ["CMD", "curl", "--fail", "--socks5", "127.0.0.1:9050","https://torproject.org"]
      interval: 30s
      timeout: 10s
      retries: 10 
    volumes:
     - bridgeconf:/opt/torconf
    mem_limit: 128m
    cpus: 0.5

  tbng-3proxy:
    restart: unless-stopped
    image: tbng-3proxy_ds
    ports: 
      - "8888:8888"
      - "1080:10800"
    links:
      - "tbng-bridge:tor"
    environment:
      - AUTH=AUTH
### change this or move to external env
      - PROXY_USERNAME=proxyuser
### change this or move to external env
      - PROXY_PASSWORD=proxypassword
    depends_on:
      tbng-bridge:
        condition: service_healthy
    mem_limit: 32m
    cpus: 0.5

volumes:
  bridgeconf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/conf/tbng-bridge"
